server:
  port: 9997
#  context-path: /clientOne #2.0不再使用此方式配置
security:
  ignored: /,/favicon.ico,/home.html,/dashboard.html,/js/**,/css/**,/webjars/**
  sessions: ALWAYS
  user:
    password: 123456
  oauth2:
    sso:
      login-path: /clientOne/login
    client:
      client-id: owen
      client-secret: owen 
      user-authorization-uri: http://127.0.0.1:8000/oauth/authorize    
      access-token-uri: http://127.0.0.1:8000/oauth/token
    resource: 
#        user-info-uri: http://127.0.0.1:8000/auth/users #返回认证服务器检查
#        prefer-token-info: false
      token-info-uri: http://127.0.0.1:8000/oauth/check_token
      prefer-token-info: true
 
 
spring:
  application:
    name: auth-sso
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name:  oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
#      username: crm_owner_user
#      password: bss_crm_test
#      filters: stat,wall
################## mysql start ############################
      driver-class-name:  com.mysql.jdbc.Driver
      #     192.168.3.150   130.75.131.211  134.224.249.39  47.94.252.160
      url: jdbc:mysql://59.110.164.254:3306/oauth-center?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: root
      password: root
      filters: stat,wall
################### mysq end l##########################
  redis:
################### redis 单机版 start ########################## 
    host: 59.110.164.254
    port: 6379    
    timeout: 3000
    database: 0
################### redis 单机版 end ##########################   
#    cluster:
#      nodes: 130.75.131.237:7000,130.75.131.238:7000,130.75.131.239:7000,130.75.131.237:7001,130.75.131.238:7001,130.75.131.239:7001
#        #130.75.131.237:7000,130.75.131.238:7000,130.75.131.239:7000,130.75.131.237:7001,130.75.131.238:7001,130.75.131.239:7001
#        #192.168.3.157:7000,192.168.3.158:7000,192.168.3.159:7000,192.168.3.157:7001,192.168.3.158:7001,192.168.3.159:7001
#    timeout: 1000 # 连接超时时间（毫秒）
#    lettuce:
#      pool:
#        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
#        max-idle: 8   # 连接池中的最大空闲连接 ，默认值也是8
#        max-wait: 100 # # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException  
#        min-idle: 2    # 连接池中的最小空闲连接 ，默认值也是0
#      shutdown-timeout: 100ms    
    
    

mybatis:
  config-location: classpath:mybatis.cfg.xml
  mapper-locations: classpath*:com/open/**/dao/*.xml  
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/
      #http://192.168.3.170:1111/eureka,http://192.168.3.171:1111/eureka,http://192.168.3.173:1111/eureka
      #http://130.75.131.243:1111/eureka/,http://130.75.131.244:1111/eureka/,http://130.75.131.245:1111/eureka/  
    registry-fetch-interval-seconds: 3  
    instance-info-replication-interval-seconds: 3   
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
#    instance-id: ${spring.application.name}:${docker.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5
 
