# 注册中心 
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 119.27.173.249:8848
        namespace: 95a4a445-f548-4c0d-98fc-a471454dabec  #命名空间 代指某个环境
  sentinel:
      transport:
        port: 8719
        # 指定sentinel 控制台的地址
        dashboard: 127.0.0.1:8080         
  jackson:
        mapper:
            ALLOW_EXPLICIT_PROPERTY_RENAMING: true
        deserialization:
            READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
        serialization:
            WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
            WRITE_DATES_AS_TIMESTAMPS: true