server:
  port: 9411
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: zipkin-server

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: http://39.108.176.135:9200
      #      username: elastic
      #      password: changeme
      cluster: elasticsearch
      index: zipkin
      index-shards: 1
      index-replicas: 1
  collector:
    kafka:
      bootstrap-servers: 39.108.176.135:9092
      zookeeper: 39.108.176.135:2181
      topic: zipkin

eureka:
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        auto-time-requests: false